name: capswriter_02
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - rich=13.9.4
  - websockets=13.1
  - numpy=2.2.3
  - typeguard=2.13.3
  - pip
  - pip:
    - sherpa-onnx==1.10.45
