name: capswriter_02
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - websockets=13.1
  - rich=13.9.4
  - keyboard=0.13.5
  - typer=0.15.1
  - watchdog=6.0.0
  - python-sounddevice=0.5.0
  - ffmpeg
  - numpy=2.2.3
  - colorama=0.4.6
  - pypinyin=0.53.0
  - srt=3.5.3
  - pip
  - pip:
    - pyclip==0.7.0

    
